# Site settings
title: Casa Cuidad
description: >
  330 E 39th St |
  25M |
  New York, NY 10016
url: ''
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Alejandro Figueroa & Cassandra Reyes-Jones'
  # email: alejandro@ideasftw.com
  # twitter_username:
  # facebook_username:
  # github_username: thejandroman
  # linkedin_username:

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jemoji
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
